/// Identifies which widget a tour step highlights; the step's text is
/// resolved separately.
enum TourStepId {
  calendarGrid,
  calendarDayList,
  calendarAddAppointment,
  calendarDayRoute,
  calendarCollapse,
  clientsSearch,
  clientsFilter,
  clientsAdd,
  clientsRow,
  employeesSearch,
  employeesAdd,
  employeesRow,
  historySearch,
  historyFilter,
  historyRow,
  liveMapRoster,
  liveMapRecenter,
  settingsAppearance,
  settingsNotifications,
  settingsReplay,
  dashboardHero,
  dashboardUpcoming,
  dashboardWorkload,
  dashboardAttention,
  dayRouteDaySwitcher,
  dayRouteEmployee,
  dayRouteStops,
  dayRouteNavigate,
  // The add-appointment walkthrough.
  apptTemplates,
  apptClient,
  apptCrew,
  apptSchedule,
  apptDetails,
  apptSave,
  // The add-client walkthrough.
  clientWho,
  clientReach,
  clientSite,
  clientSave,
  // The invite-a-person walkthrough.
  personDetails,
  personJobTitle,
  personColour,
  personCreate,
}
